### ISSUE TITLE
Support for Translations

### ISSUE THREAD

**Issue by dennisausbremen** [openhab/org.openhab.ui.habpanel#131]
First things first. Thank you for the tremendous effort put into this project.
What caught my eye was the missing possibility to select a language for habpanel.
That would be pretty nice to have and could be accomplished by using something like [angular-translate](https://github.com/angular-translate/angular-translate).

Keep up the good work. ;)

Dennis

**Comment by ghys** [comment]
Yes, this was in my mind too - starting with date/time formats.
I'll consider it for an upcoming milestone!

**Comment by dennisausbremen** [comment]
Great

**Comment by LuckyMallari** [comment]
I have used ng-translate at work and is currently in production. The biggest issue is maintaining the translation database as user xyz wants a different translation as user abc. In such cases, we should design it in a way where they can set the translation db using JSON to feed ng-translate.

**Comment by nilton1179** [comment]
Sorry for my ignorance, but how can I change the language of the HABPANEL labels? (Ex.: Backdrop icon, Open, Close, Save, etc)

**Comment by fab33** [comment]
It will be fine to add support for number like {{itemValue('Compteur_WhHC')/1000 | number:0}} to (un)set comma between thousands and hundreds.

**Comment by JueBag** [comment]
Is this still on the ToDo List?

**Comment by ghys** [comment]
Sure - just not on really top of it 😉

**Comment by ghys** [comment]
The locale support for date/time and numbers is on the way in #256.
I'm not sure the complete translation of the user interface is viable though.
Maybe only translate the part visible by end users when the dashboard are running - not the designer and admin screen - settings etc.?
Wdyt?

**Comment by gersilex** [comment]
@ghys Do you want to minimize the required effort of translating the whole application or do you think that people might want to translate the dashboards that face the end-user but want to keep the settings and stuff in english? I just didn't understand why you are asking, yet.

**Comment by ghys** [comment]
What I meant is, maybe translating only the parts a non-technical user will see is enough - which happens to be not much actually, now that the dates are covered: a few tooltips here and there. Not to mention it's quite stable so there wouldn't be a need to update those translations often.

The settings dialogs and screens could IMO probably stay in English since the target audience of those is openHAB administrators and tech-savvy people who can probably read English (since they managed to install openHAB).

That being said I'm open to other opinions! :)

**Comment by gersilex** [comment]
I agree. Probably best to make it possible to translate everything but just don't provide any translations in the backend, right? So if we ever change our mind and want to translate everything, we could just provide them.

**Comment by ghys** [comment]
That would mean going over all source code files and replacing occurences of English text by translation IDs - what I wanted to avoid ;)

**Comment by gersilex** [comment]
Alright, still makes sense :D Have my thumbs up: :+1:

**Comment by LuckyMallari** [comment]
Using translation keys instead of literal text IS the only way to support localization. No other way around it. We did at work but we started with translation keys right at the beginning. It's a one time effort. You can always provide English mapping as fallback so keys that aren't translated would still make sense and not just appear as key on the front end. 

For our QA, keys with no translation are left as is so that they can easily find and report them but that's not the case here.

**Comment by ghys** [comment]
For the record: 

> That would mean going over all source code files and replacing occurences of English text by translation IDs - what I wanted to avoid ;)

I did that in the end, so HABPanel can now be completely translated, this issue is therefore closed for good!

We'll use https://crowdin.com for the localizaton management; details to follow (and on community.openhab.org).

**Comment by kaikreuzer** [comment]
@ghys I have created https://crowdin.com/project/openhab-habpanel
Do you already have a crowdin account, so that I can make you a manager of it?
@ThomDietrich Fyi, I named it "openhab-habpanel" and not "org.openhab.ui.habpanel", because Crowdin does not allow dots in the name/url and without them, it didn't look good 😲 .

**Comment by ghys** [comment]
Thanks @kaikreuzer!
My crowdin account is ghys (I signed up with GitHub).

**Comment by kaikreuzer** [comment]
Thanks! (I see I should actually rather have commented on https://github.com/openhab/org.openhab.ui.habpanel/pull/256...)
