### ISSUE TITLE
Extend HABPanel documentation

### ISSUE THREAD

**Issue by kubawolanin** [openhab/org.openhab.ui.habpanel#138]
[This post](https://community.openhab.org/t/habpanel-documentation/21594) was a reason to submit this issue.
We need a good documentation for HABPanel functionality.
Right now it's seen as a single page in [our docs](http://docs.openhab.org/addons/uis/habpanel/readme.html) so I wonder if we can divide it into sections or pages? I've seen some README pages having Table of Content, so maybe this is a way to go.
Pinging @ThomDietrich for awareness :)

I'd see the following sections to be described:

* Introduction
* Dashboards `Appearance?`
    - Layout
    - Theming
* Widgets
    - Built-in widgets
    - Custom widgets
* Data storage `difference between local and permanent storage`
* Speech & Audio
    - Spoken feedback
    - Speech recognition
* Examples `maybe `[`demo dashboards`](http://demo.openhab.org:8080/habpanel/index.html#/) `available to download?`

I'm willing to write about Speech and Audio for now! :)
Cheers

**Comment by ghys** [comment]
Yes, we discussed this last week in another thread, but the documentation should now be brought up to par, I have every intention of doing so in the upcoming weeks.
I like your proposal!

**Comment by ThomDietrich** [comment]
Just for reference: https://github.com/openhab/openhab-docs/pull/253/files/7f15dbdaac54b469912135edb3a8b4da801c8e08#diff-e7268aed15098f8d1f67447185bcb977

Good luck!! ;)

**Comment by ThomDietrich** [comment]
@kubawolanin @ghys where would you like to present this content? I think extending [one page](http://docs.openhab.org/addons/uis/habpanel/readme.html) is a good approach, see [sitemaps](http://docs.openhab.org/configuration/sitemaps.html) as a similar example.

However this is of course totally up to you! Do however you feel it fits best into docs.

**Comment by ghys** [comment]
@ThomDietrich @kubawolanin  I think the one page approach is fine, but I have another proposal I'd like to share:

- the current page stays and is extended with an extensive description of the major end user features: concepts, dashboard design, description of the standard widgets and their settings, a functional description of custom widgets, storage, audio, etc.
- another page (perhaps in the Developer Guide section? where though?) centered around the template system for developing new widgets - there's a lot to write about in this area which is probably for more advanced users: it could contain a tutorial (probably a rewrite of [this](https://community.openhab.org/t/template-widget-tutorial-examples-make-your-own-widget/14211?u=ysc)), what's exactly available for use, links to important pages in AngularJS docs, some tips & tricks, a few nice examples gathered from the forum...
A link to this "develop HABPanel templates" page to this would be provided in the relevant sections (Template widget, custom widgets) of the first page.

On top of that I think a quick walkthrough in the Beginner tutorial would be a good thing (since HABPanel is installed by default with all packages but one, new users are likely to want to learn about it), I would put it below "Creating a sitemap" or maybe "Working with rules" to be consistent with the user story.

What do you think?

**Comment by ghys** [comment]
> demo dashboards available to download?

This demo panel config is now automatically imported and set as default when installing the demo package, and contrary to demo.openhab.org editing is allowed for users to play with.

**Comment by kubawolanin** [comment]
> What do you think?

I think that it all depends on actual content we'll produce :). Two-page approach is more future-proof and leaves us a room for further docs.
But looking at [current state of User Interfaces chapter](http://docs.openhab.org/addons/uis.html) I feel that we should start with putting it on one page with descriptive ToC, as it'd be easier to find all necessary content + more straightforward navigation through the content.

**Comment by ghys** [comment]
Update on this front!
See #159 and https://github.com/ghys/habpanel/blob/documentation/doc/index.md.
I plan on adding descriptions of the standard widgets configuration settings, and the chapter on developing templates & custom widgets later.

Feedback appreciated :smile:

**Comment by ghys** [comment]
The documentation is being moved to the openhab-docs repo, see https://github.com/openhab/openhab-docs/pull/372 - closing this issue.
