### ISSUE TITLE
Allow javascript in custom widgets

### ISSUE THREAD

**Issue by TiS** [openhab/org.openhab.ui.habpanel#162]
Custom/template widgets are quite powerfull. But they have a huge limitation: the only thing you can edit is a template.

Not everything can be achieved by using just angular expressions. One example is value formatting in knob widget. ng-knob has a configuration property named `inputFormatter`, but it accepts only function objects, something you cannot declare inside of a template.

Another example is detecting a type of item value. Again with knob widget - it requires values to be numbers. As in configuration I can inject any item (string, datetime etc) - when I choose wrong it throws errors. I'd rather, that it should show blank space then, as in original knob widget. But it's hard/impossible to code as just Angular expressions, without using `Number.isNumber`, `parseInt` etc.

I was thinking of adding new editor field to a template widget / custom widget (might be hidden by default), where you can put javascript code. This code can then be compiled and invoked. It may take `$scope` as an argument, so user can use `$scope.$watch`, bind new scope functions, access `$scope.config` etc.

I have created a simple plunk proving, that such thing is indeed possible. Here's the URL: https://plnkr.co/edit/14h3vI1qs8KxWUimkTwA?p=preview

If I find some time, I'll try to prepare PR for this feature, but I cannot guarantee that.

**Comment by ghys** [comment]
I had this idea some time ago, but decided against it because of security issues, at least until some protection measure like access control is in place at the server-level. Without it, the injection of malicious code (i.e. XSS attacks) is made trivial; for example, every item update could be sent to an external server without you noticing.
(As a side note, even allowing externally-controlled Angular templates and expressions should be considered dangerous, because there are ways to escape the expression sandbox which [has been removed altogether in 1.6](https://docs.angularjs.org/guide/security) - HABPanel still uses 1.5).

You can however lazy-load additional code - still considered an advanced use case - with the ocLazyLoad directive in your template, but there is a Content Security Policy in place to restrict them to the openHAB server, so you have to put them in your `static` folder (`conf/html`).

For example:
_/conf/html/mycontroller.js:_
```js
angular
    .module('app.widgets')
    .controller('MyWidgetCtrl', testCtrl);

testCtrl.$inject = ['$scope', 'OHService'];
function testCtrl($scope, OHService) {
  var vm = this;
  vm.myvalue = "testing123";

  OHService.onUpdate($scope, 'Yamaha_Input', function () {
    var item = OHService.getItem('Yamaha_Input');
    if (item) {
      vm.myitem = item.state;
    }
  });

}
```

_Widget template:_
```html
<div oc-lazy-load="['/static/mycontroller.js']">
  <div ng-controller="MyWidgetCtrl as myctrl">
    <input class="form-control" type='text' ng-model="myctrl.myitem" />
  </div>
</div>
```

(Note the "as myctrl" syntax and the var vm = this in the controller, this way you still have access to the methods in the parent scope - the template widget itself - if you need them).

You could also build a complete directive with its own template etc.
