### ISSUE TITLE
Habpanel shows Connection lost! Trying  to reconnect

### ISSUE THREAD

**Issue by amarpulli544** [openhab/org.openhab.ui.habpanel#184]
Hello @ghys ,

Habpanel displays Connection lost! Trying to reconnect in my sever. 
How I can fix this issue .

Thanks
Amar.

**Comment by ghys** [comment]
Hi, usually this means the connection to the events endpoint is not working because of a configuration error. Open the browser's development tools with F12 (in Chrome) and check the Console and Network tab. There should be errors (in red) along with more details on what's wrong with your installation.

(Also, https://community.openhab.org/ is better suited for user support requests - more people can help you over there; GitHub issues are more for tracking bugs and new features) 😄

**Comment by amarpulli544** [comment]
Hi @ghys ,

Yes, i am getting below errors in chrome browser.
![habpanel](https://user-images.githubusercontent.com/16384828/27022444-97ec30c0-4f6b-11e7-8675-ceb686f0974d.png)

 I just made some modifications in habapnel bundle . What are there I  just replaced  `org.openhab.ui.habpanel.internal` instead  of `org.openhab.ui.habpanel` in export package section.
When I did same thing in previous habpanel bundle, but didn't get this type of issues.
But now i am trying to build previous habpanel bundle , it doesn't work for me. Previous habpanel also showing same thing.

Thanks
Amar.

**Comment by ghys** [comment]
Hmm, strange...
You could maybe try clicking on the URL after $injector:moduleerr as it will display the entire error message in the AngularJS site. Also compare your vendor.js file with the official bundle's version, are you sure they aren't different? It hasn't changed for 3 months in this repo.

> What are there I just replaced org.openhab.ui.habpanel.internal instead of org.openhab.ui.habpanel in export package section.

Unrelated to your problem, but I don't know why you would want to do that, it's discouraged by openHAB/ESH coding guidelines (http://docs.openhab.org/developers/development/guidelines.html § B.6.)

**Comment by amarpulli544** [comment]
Sorry for made modification in habpanel repo. But we are using package name `org.openhab.ui.habpanel.internal` in habpanel repo. Thats why  i am just changing name.
