### ISSUE TITLE
Item states going to from ON state to OFF state, while refresh the habpanel

### ISSUE THREAD

**Issue by amarpulli544** [openhab/org.openhab.ui.habpanel#245]
Hi @ghys ,

Item states are going to from ON state to OFF state, When we could refresh the habpanel in chrome browser. I have a set up one xbee device is a connected to software and other xbee device connected to hardware side. But here when i got data from hardware side, like Switch  ON. When I just did that refresh the habpanel , the state going to be OFF state.
But I received Switch ON state from hardware side. How to fix this thing.
I have been monitored console file at habpanel side, it showing " Loaded openhab items" while refresh habpanel page.

Thanks and Regards,
Amar Pulli.

**Comment by ghys** [comment]
Check your openHAB logs for something like:
`21:03:19.766 [INFO ] [marthome.event.ItemStateChangedEvent] - <Item> changed from OFF to ON`
If you don't see this you have a problem with your xbee binding/configuration.
The event source connection between HABPanel and openHAB might also be broken (unlikely because it tries to reconnect and restore the item states automatically in those cases). Usually a restart of the openHAB server + a refresh of the HABPanel page fixes the problem.

In any case I don't think it's an issue with HABPanel itself, and I'm not familiar with the xbee binding so can't help you with that (unless you're certain you don't have problems with other UIs like Basic UI); I'd invite you to try to get help on https://community.openhab.org instead of here.
