### ISSUE TITLE
Missing ESH Classic Icons in HabPanel 

### ISSUE THREAD

**Issue by DJDeepT** [openhab/org.openhab.ui.habpanel#260]
Since a few month there are missing Icons in HabPanel ESH Classic
I read that there were do changes. But how can i update my System that there are all Icon there again? 
The Battery Icon also does not change in Red if Empty.
What can i do?

![missing icons](https://user-images.githubusercontent.com/35026194/34479176-6af28b98-efa5-11e7-9784-f667178b7be9.jpg)

Thanks for Help.

Tobi

**Comment by ghys** [comment]
Indeed, I haven't noticed, thanks for reporting.
The list of icons is in this file: https://github.com/openhab/org.openhab.ui.habpanel/blob/master/web/assets/icons/eclipse-smarthome-classic.list.json
and is now outdated, so it should be updated.

You can use "custom icon" in the iconset dropdown and type the name of the icon you want to use from http://docs.openhab.org/addons/iconsets/classic/readme.html instead of using the list.
