### ISSUE TITLE
Missing Linked Things After Reboot Raspberry Pi with Openhabian 1.4

### ISSUE THREAD

**Issue by DJDeepT** [openhab/org.openhab.ui.habpanel#261]
Hello.
Since installing OH 1.4 i see, that Linked Channels in PaperUI are unlinked after a Reboot.
Not always the same things/channels. Different Bindings.
What can i do here? Sometimes i have to restart my pi and then i can't always go through all Things (more than ~130) and check this.

Thanks

Tobi

**Comment by ghys** [comment]
This is not the right place to report since this is unrelated to HABPanel.
Please use https://community.openhab.org - it's the preferred channel for support and you'll likely find people who can help you there.
If there's really a bug in either Eclipse SmartHome, openHABian or the openHAB distribution you will be directed to the proper place to submit a issue.
