### ISSUE TITLE
Problems with height "detection" in css and html

### ISSUE THREAD

**Issue by claell** [openhab/org.openhab.ui.habpanel#303]
I have been facing problems with the height detection of the viewport.

First time I noticed it was when I used `vh` instead of `px` for text size, which behaved different from `vw`.

Now I tried to apply 100% height to an image. While width works and the image is resized responsive to the width of the widget, the height is constant.

This lead me to think that there is some problem with the detection of the height, but I might be wrong.

**Comment by ghys** [comment]
You're probably wrong, there is no "height detection" besides what the browser is offering (`vw` and `vh`) - vertical positioning is infamously a major pain point in CSS...
https://stackoverflow.com/questions/1575141/how-to-make-a-div-100-height-of-the-browser-window
("height: 100%" means 100% of the height of the container which might not have a height)

This issue is also really too vague and not actionable, if you want to discuss widget development please use the forum instead: https://community.openhab.org/c/apps-services/habpanel - Thanks!
