### ISSUE TITLE
New weather widget

### ISSUE THREAD

**Issue by kubawolanin** [openhab/org.openhab.ui.habpanel#46]
So I'm working on the weather widget for HABPanel :)

Right now I'm working on cleaning up the code (I have like 9 items to update from openHAB. It needs some a factory pattern of some sort to get it right). 
I also need to add more configurable options (like icon animation, maybe different layouts).

Let me know what you think!

I'm submitting this issue to start a discussion. Later, when my code will be polished and working, I'll post a pull request.

Cheers!

![weather](https://cloud.githubusercontent.com/assets/2270505/19412116/f387718e-930e-11e6-94d6-d717c2b4edde.PNG)
##

**Comment by neohusky** [comment]
Excellent work. This is a pleasant surprise. I can't wait to see this develop.

**Comment by ghys** [comment]
Ah, the obligatory weather widget :)
Cool! - provided it doesn't leave a huge footprint on the codebase of course ;)
How do you manage the icons?

**Comment by kubawolanin** [comment]
Footprint? Same as other widgets I suppose.
Icons are stored in separate svg files.

**Comment by ghys** [comment]
Ok cool. :)
I actually think the weather icons would be good candidates for building a proper ESH [IconProvider](http://docs.openhab.org/addons/uis.html#iconsets) ([code](https://github.com/eclipse/smarthome/blob/master/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/src/main/java/org/eclipse/smarthome/ui/iconset/classic/internal/ClassicIconProvider.java)), since they would be a scoped set with well-known names (and I realise this contrasts with those built-in user selectable backdrops, but the use case is different here).
You could even have an icon set picker populated with the `/rest/iconsets` API endpoint result, letting users select their own weather iconset if they happen to have several registered. :)

**Comment by ghys** [comment]
Wow, those animated icons certainly look nice!
I checked the license and while attribution isn't required, a mention in the about.html is in order.
Curious what you'll come up with!

**Comment by korg1000** [comment]
Its already working? I downloaded the last version from habpanel and cannot see the weather widget.

**Comment by NCO3** [comment]
I would love to use it as well.
Where could I get it please?

**Comment by kubawolanin** [comment]
I was pretty busy with my daily tasks lastly, but I'm back on the road.
Yesterday I've merged latest and greatest HABPanel to [my repo](https://github.com/kubawolanin/org.openhab.ui.habpanel) so I'm able to continue working on that widget.
I will submit my pull request in upcoming week.

**Comment by kubawolanin** [comment]
Implemented in #72

**Comment by NCO3** [comment]
Hi
Can I just donwload the weather widget code somewhere?

**Comment by kubawolanin** [comment]
Hey @NCO3 (and pinging @korg1000 @neohusky too)
I can finally answer - yes 🙂 
I declined my previous pull request.

Here's my custom widget utilizing @ghys's animated iconset:
https://community.openhab.org/t/custom-widget-current-weather/18216

I think we can close this issue now.
Thank you,
Kuba

**Comment by neohusky** [comment]
Awesome. I'll try it out soon.
