### ISSUE TITLE
Include settings and custom widgets in the local panel configuration editor

### ISSUE THREAD

**Issue by wookienow** [openhab/org.openhab.ui.habpanel#50]
Is it possible to share configured screens on Openhab 1.8 or is this only available in 2?
##

**Comment by ghys** [comment]
You can do it in the advanced settings: Click on the "Edit the local panel configuration (experts only)" link, then copy the whole text in the editor to the clipboard, send it to another device with the method of your choice, and paste it back on the same screen then click Save.

I'm leaving the issue open because I wanted to use the HTML5 File API to interact with files on the local device (instead of copy-pasting JSON text).

**Comment by jenskastensson** [comment]
Hi, thanks for the very nice dashboard!
Question on the import/export topic:
1. Start with a nice dashboard (here: the demo config with lockediting false)
2. Open Settings |  Local panel configuration editor and Export, Save as "DEMO.json"
3. Duplicate to "DEMO-MOD.json" and rename something ('Floor' -> 'FLOOOR' in the attached file) and save the file.
4. Open Settings |  Local panel configuration editor and select "Save the current configuration to a new panel configuration " and name it MOD (It is a clone of Demo at this stage)
5. Select "Edit the local panel configuration (experts only) " and Import "DEMO-MOD.json" and Save
6. Refresh / F5 and Open Settings -> Panel Config is now MOD and the with 'FLOOOR'
7. Open HABPanel, the toplevel rows and cols are lost, Ground FLOOR is full witdth
8. Export the configuration and save as "DEMO-MOD-export.json"

I was expecting the modified dashboard to be identical to the original? 
Can you elaborate why and how this works, maybe a common use case, potentially a Clone button is interesting to have?
[demo.zip](https://github.com/openhab/org.openhab.ui.habpanel/files/666117/demo.zip)

**Comment by ghys** [comment]
That's likely due to the fact that the "local configuration editor" is currently dealing with the array of dashboards only, while settings (number of columns in the home page, theme, custom widgets etc.) are treated separately. So you can lose those settings and that can mess up the main menu (you're back to 1 column).

This is wrong and for historical reasons only, I'll probably change it at some point to logically include settings and custom widgets as well.

**Comment by jenskastensson** [comment]
Thx, do you mind if I open a new issue (or maybe re-open this)?

**Comment by ghys** [comment]
Not at all. I'll edit the title as well.

**Comment by ghys** [comment]
Finally got around to it 😁
