### ISSUE TITLE
Custom widgets - add "default" fields value

### ISSUE THREAD

**Issue by kubawolanin** [openhab/org.openhab.ui.habpanel#73]
Hello!
I'm creating a new widget that has decent amount of settings.
I have two suggestions:
* To add a new field "Default" to the setting form (along with "Type", "Id" and "Label"). 
This will allow us to set constraints for given fields
* Format the forms a little bit, e.g.
```
.widgetdesigner .well {
    width: 50%;
    display: inline-block;
}
```
This way we utilize some of the white space.

**Comment by kubawolanin** [comment]
Just FYI - using simple Angular expressions allows you to manage the default state easily :)
```js
nav.directions {
  --bg-color: transparent;
  --btn-color: {{config.btn_color || '#fff'}};
  --btn-active: #eee;
  --text-color: #222;
 ...
}
```

**Comment by ghys** [comment]
Yep, the default value is something that was actually there at first but I removed it because reasons, I don't remember why :) But I agree, it should be there.

About the layout changes in the settings list:
Keep in mind HABPanel works on phones so the interface should be responsive when on a narrow screen, maybe Boostrap's `col-sm-6` is a better option.
It would also have to play nicely with the reordering of settings that should/will also be implemented.
