### ISSUE TITLE
Enhancement: Responsive grid

### ISSUE THREAD

**Issue by kubawolanin** [openhab/org.openhab.ui.habpanel#96]
Hello!
HABpanel is using [angular-gridster](https://github.com/ManifestWebDesign/angular-gridster) for layout management.
What do you think of applying responsive styles to it? [There were some attempts](https://github.com/ducksboard/gridster.js/issues/475) already to make a nice scalable grid for all the devices.

The only concern I have is that some inner parts of the widgets (icons, mostly) are not scalable/pixel-based.

We could also utilize [`mobileBreakPoint`](https://github.com/ManifestWebDesign/angular-gridster#via-scope) property for the widgets?

**Comment by ghys** [comment]
The `mobileBreakPoint` was disabled because it's impossible to reorder the tiles when it's in effect. As for the dynamic columns (if I understand correctly) why not, but I don't know how it would behave especially in the editor. I like the idea of WYSIWYG during the design phase.
The idea at the time was, design with the target device in mind and a fixed orientation (since a majority of users use it with fixed tablets around the house).

And you're right about the issues with icons, labels and some widgets - notably knobs, sliders and color pickers - but this could be solved.

**Comment by jenskastensson** [comment]
Mobile responsiveness would be a nice feature, how about applying the mobileBreakPoint when design mode is disabled (panel config read-only) ?
